name: CI
on: [push, pull_request]
jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Dependencies
        run: sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list; sudo apt-get update; sudo apt-get install xvfb; sudo apt-get install libgtk-3-dev; sudo apt-get install libgdk-pixbuf2.0-dev
      - name: Linking gdk-pixbuf
        run: sudo ln -s /usr/include/gdk-pixbuf-2.0/gdk-pixbuf /usr/include/gdk-pixbuf
      - name: Installing V
        run: cd ~; git clone https://github.com/vlang/v.git; cd v; make; sudo ./v symlink
      - uses: actions/checkout@v2

      - name: Running Test (TCC)
        env:
          VFLAGS: -cc tcc  -cg -showcc
        run: xvfb-run make test
        continue-on-error: true

      - name: Running Test (CLANG)
        env:
          VFLAGS: -cc clang -cg -showcc
        run: xvfb-run make test
        continue-on-error: true

      - name: Running Test (GCC)
        env:
          VFLAGS: -cc gcc -cg -showcc
        run: xvfb-run make test
        continue-on-error: true
